create-routeToRegisterConfigV1
tradeupgroup/power_bi_management_api pull request #1
Opened 2023-06-26 17:17 UTC by PaivaTradeUp

###DESCRIÇÃO
CRIAÇÃO DE UMA ROTA PARA SALVAR AS CONFIGS DE UM DAHSBOARD

###TEST
![image](https://github.com/tradeupgroup/power_bi_management_api/assets/131169245/94703db3-10b5-4950-9f78-abd61af2dad9)

###PSR TEST
![image](https://github.com/tradeupgroup/power_bi_management_api/assets/131169245/effa1b97-40c2-431f-b7d6-c3430b3f9729)

2023-07-05 12:17 UTC, lecastro approved these changes

2023-07-05 12:19 UTC, VictorSantosDev commented on App/Authentication/Application/Input/InputAuthentication.php
> +        null|int $userId,
Deve ser nulo ou não?

2023-07-05 12:21 UTC, VictorSantosDev commented on App/Authentication/Application/Output/OutputExample.php
> +    public function jsonSerialize(): array
```suggestion
    /** @return array<string> */
    public function jsonSerialize(): array
```

2023-07-05 12:22 UTC, VictorSantosDev commented on App/Authentication/Controller/RegisterController.php
>      }
```suggestion
```

2023-07-05 12:23 UTC, VictorSantosDev commented on App/Authentication/Controller/RegisterController.php
> +    public function getAuthenticationApplication(): RegisterApplication
```suggestion
    private function getAuthenticationApplication(): RegisterApplication
```

2023-07-05 12:27 UTC, VictorSantosDev commented on App/Authentication/Infrastructure/Entity/RegisterConfigEntity.php
> +}
last line empty

2023-07-05 12:28 UTC, lcmialichi requested changes

2023-07-05 12:28 UTC, lcmialichi commented on App/Authentication/Infrastructure/Entity/RegisterConfigEntity.php
> +}
quebrar linha

2023-07-05 12:28 UTC, lcmialichi commented on App/Authentication/Application/Input/InputAuthentication.php
> +    public function getConfig()
```suggestion
    public function getConfig(): Config
```

2023-07-05 12:28 UTC, lcmialichi commented on App/Authentication/Application/Input/InputAuthentication.php
> +    private function isValid(null|string $value): void
```suggestion
    private function isNotEmpty(null|string $value): void
```

2023-07-05 12:28 UTC, lcmialichi commented on App/Authentication/Application/Output/OutputExample.php
> +    public function jsonSerialize(): array
dockblock

2023-07-05 12:28 UTC, lcmialichi commented on App/Authentication/Domain/Entity/Active.php
usa o Status do kernel ao invez desse enum

2023-07-05 12:28 UTC, lcmialichi commented on App/Authentication/Domain/Entity/Config.php
> +    // }
remover função comentada

2023-07-05 12:28 UTC, lcmialichi commented on App/Authentication/Domain/Entity/Config.php
> +    public function jsonSerialize() : mixed
dockblock

2023-07-05 12:28 UTC, lcmialichi commented on App/Authentication/Domain/Repository/RegisterRepository.php
> +    public function checkSourceConfig(string $sourceConfig);
retorno?

2023-07-05 12:28 UTC, lcmialichi commented on App/Authentication/Infrastructure/Entity/ExampleDomainContextEntity.php
porque isso ta aqui? kkk

2023-07-05 12:28 UTC, lcmialichi commented on Config/LanguageTranslation/Language/BrazilianPortuguese.php
> +            'POWERBI_DASHBOARD_ERROR'                   => 'Erro embedagem dashboard.',
embedage,?

2023-07-05 12:28 UTC, lcmialichi commented on Test/App/Authentication/Domain/Service/RegisterServiceTest.php
> +    private function instaceConfig()
```suggestion
    private function instaceConfig(): Config
```

2023-07-05 12:29 UTC, VictorSantosDev commented on App/Authentication/Infrastructure/Repository/RegisterRepository.php
> +
docBlock

2023-07-12 16:34 UTC, lecastro approved these changes

2023-07-12 16:34 UTC, merged